models:
  - type: main
    engine: openai
    model: llama-3.3-70b-versatile
    parameters:
      base_url: "https://api.groq.com/openai/v1"

rails:
  input:
    flows:
      - check off topic
      - check prompt injection

instructions:
  - type: general
    content: |
      أنت مساعد ذكي مخصص فقط للحسابات والرياضيات والتحليل الفني للأسهم.